//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Walmart.Prova.Business.CidadeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CidadeService.ICidade")]
    public interface ICidade {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICidade/Add", ReplyAction="http://tempuri.org/ICidade/AddResponse")]
        string Add(Walmart.Prova.Model.Cidade cidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICidade/Update", ReplyAction="http://tempuri.org/ICidade/UpdateResponse")]
        string Update(Walmart.Prova.Model.Cidade cidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICidade/Delete", ReplyAction="http://tempuri.org/ICidade/DeleteResponse")]
        string Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICidade/Get", ReplyAction="http://tempuri.org/ICidade/GetResponse")]
        Walmart.Prova.Model.Cidade Get(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICidadeChannel : Walmart.Prova.Business.CidadeService.ICidade, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CidadeClient : System.ServiceModel.ClientBase<Walmart.Prova.Business.CidadeService.ICidade>, Walmart.Prova.Business.CidadeService.ICidade {
        
        public CidadeClient() {
        }
        
        public CidadeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CidadeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CidadeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CidadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Add(Walmart.Prova.Model.Cidade cidade) {
            return base.Channel.Add(cidade);
        }
        
        public string Update(Walmart.Prova.Model.Cidade cidade) {
            return base.Channel.Update(cidade);
        }
        
        public string Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public Walmart.Prova.Model.Cidade Get(string id) {
            return base.Channel.Get(id);
        }
    }
}
